lend/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

simplediary/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('petroleum/', include('petroleum.urls')),
    # login and registration
    path('login/', views.LoginView.as_view(), name='login'),
    path('home/', include('accounts.urls')),
]

tasks/urls.py
from django.urls import path
from . import views
from .views import TaskCreateFormView, TaskUpdateView, TaskDeleteView

urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('create_task/', TaskCreateFormView.as_view(), name='task_create'),
    path('edit_task/<int:pk>', TaskUpdateView.as_view(), name='task_edit'),
    path('<pk>/delete/', TaskDeleteView.as_view()),
    path('download_csv', views.download_task_list, name='down_task_list_csv'),
]

tasks/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

# specify transaction_type
STATUS_CHOICES = (
    ("pending", "pending"),
    ("completed", "completed"),
)

# Create your models here.


class Task(models.Model):
    date = models.DateField(default=datetime.today)
    created_by = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=225)
    contact_details = models.CharField(max_length=15)
    description = models.TextField(null=True, blank=True)
    work_status = models.CharField(
        max_length=225, default="pending", choices=STATUS_CHOICES)
    amount_status = models.CharField(
        default="pending", max_length=225, choices=STATUS_CHOICES)
    total_amount = models.PositiveBigIntegerField()
    advance_amount = models.PositiveBigIntegerField()
    pending_amount = models.PositiveBigIntegerField()
    remark = models.TextField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "tasks"
        ordering = ['-id']

    def __str__(self): 
        return self.customer_name 

    
    

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task

        fields = (
            "date",
            "customer_name",
            "contact_details",
            "description",
            "work_status",
            "amount_status",
            "total_amount",
            "advance_amount",
            "pending_amount",
            "remark",
        )

tasks/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Task
from django.views.generic.edit import DeleteView, FormView, UpdateView
from .forms import TaskForm
import csv
import time
from django.db.models import Sum
from django.urls import reverse_lazy

# from django.urls import reverse

# Create your views here.


class TaskCreateFormView(FormView):
    model = Task
    template_name = "task_form.html"
    extra_context = {"pageName": "Create a Task"}
    form_class = TaskForm
    success_url = "/tasks"

    def form_valid(self, form):
        task = form.save(commit=False)
        task.created_by_id = self.request.user.id
        task.save()
        return super().form_valid(form)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "task_form.html"
    form_class = TaskForm
    success_url = "/tasks"
    extra_context = {"pageName": "Edit Task"}

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# @login_required
class TaskDeleteView(DeleteView):
    model = Task
    
    success_url = "/tasks"
    # success_url = reverse_lazy('task_list')
    
    
    
    
    
    



@login_required
def task_list(request):
    Tasks = Task.objects.all().filter(created_by_id=request.user.id)
    page_number = request.GET.get("page")

    all_task_count = Tasks.count()
    # count total pending taks
    count_pending_work = Tasks.filter(work_status="pending").count()
    # sum of pending task amount
    total_pending_amount = Tasks.filter(work_status="pending").aggregate(
        Sum("pending_amount")
    )
    # count total pending taks
    advance_amount = Tasks.filter(work_status="pending").filter(
        amount_status="completed"
    )

    work_status = request.GET.get("work_status")
    if work_status:
        Tasks = Tasks.filter(work_status=work_status)
    amount_status = request.GET.get("amount_status")
    if amount_status:
        Tasks = Tasks.filter(amount_status=amount_status)
    
    start_date = request.GET.get("start_date")
    if start_date:
        Tasks = Tasks.filter(date__gte=start_date)
    end_date = request.GET.get("end_date")
    if end_date:
        Tasks = Tasks.filter(date__lte=end_date)



    paginator = Paginator(Tasks, per_page=25)
    tasks = paginator.get_page(page_number)
    context = {
        "tasks": tasks,
        "pageName": "Task List",
        "allTaskCount": all_task_count,
        "countPendingWork": count_pending_work,
        "totalPendingAmount": total_pending_amount,
        "advanceAmount": advance_amount,
    }
    return render(request, "pages/task_list.html", context)


@login_required
def download_task_list(request):
    response = HttpResponse(
        content_type="text/csv",
        headers={
            "Content-Disposition": 'attachment; filename="sa_'
            + str(time.time())
            + '.csv"'
        },
    )
    Tasks = Task.objects.all().filter(created_by_id=request.user.id)
    work_status = request.GET.get("work_status")
    if work_status:
        Tasks = Tasks.filter(work_status=work_status)

    start_date = request.GET.get("start_date")
    if start_date:
        Tasks = Tasks.filter(date__gte=start_date)
    end_date = request.GET.get("end_date")
    if end_date:
        Tasks = Tasks.filter(date__lte=end_date)


    # page_number = request.GET.get('page')
    # paginator = Paginator(Tasks, 10)
    # tasks = paginator.get_page(page_number)

    writer = csv.writer(response)
    writer.writerow(["Date", "Customer Name", "Contact Details", "Description", "Work status", "Amount", "Total amount", "Advance amount", "Pending amount", "Remark"])
    tsks = Tasks.values_list("date","customer_name", "contact_details", "description", "work_status", "amount_status", "total_amount", "advance_amount", "pending_amount", "remark")
    for tsk in tsks:
        writer.writerow(tsk)
    return response

tasks/templates/task_form.html
{% extends 'admin_base.html'%}
{% load crispy_forms_tags %}

{% block main %}

<form method="POST">
    {% csrf_token %}
    <div class="row">
        <div id="div_id_date" class="mb-3 col">
                <label for="id_date" class="form-label requiredField">
                    Date<span class="asteriskField">*</span>
                </label>
                
                <input type="date" name="date" class="dateinput form-control" value="{{ form.date.value|date:"Y-m-d" }}" required id="id_date">
        </div>
        <div id="div_id_customer_name" class="mb-3 col">
            {{ form.customer_name|as_crispy_field }}

        </div>

    </div>
    <div class="row">

        <div id="div_id_contact_details" class="mb-3 col">
            {{ form.contact_details|as_crispy_field }}
        </div>
        <div id="div_id_description" class="mb-3 col">
            <label for="id_description" class="form-label"> Description </label>
            <textarea name="description" rows="1" class="textarea form-control" id="id_description">{{ form.description.value }}</textarea>
        </div>
    </div>
    <div class="row">
        <div id="div_id_work_status" class="mb-3 col">
            {{ form.work_status|as_crispy_field }}
        </div>
        <div id="div_id_amount_status" class="mb-3 col">
            {{ form.amount_status|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div id="div_id_total_amount" class="mb-3 col">
            {{ form.total_amount|as_crispy_field }}
        </div>
        <div id="div_id_advance_amount" class="mb-3 col">
            {{ form.advance_amount|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div id="div_id_pending_amount" class="mb-3 col">
            {{ form.pending_amount|as_crispy_field }}
        </div>
        <div id="div_id_remark" class="mb-3 col">
            <label for="id_remark" class="form-label"> Remark </label>
            <textarea name="remark" rows="1" class="textarea form-control" id="id_remark">{{ form.remark.value }}</textarea>
        </div>
    </div>

    <input type="submit" class="btn btn-primary" value="Save record">

</form>
{% endblock %}